version: '3.8'
services:
  node-app:
    build:
      context: .
      args: 
        NODE_ENV: development
    volumes:
      - ./:/app:ro
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - MONGO_USER=ridoy
      - MONGO_PASSWORD=password
    command: npm run dev
  mongo:
    environment:
      - MONGO_INITDB_ROOT_USERNAME=ridoy
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongo-db:/data/db
    ports:
      - "27017:27017"
volumes:
  mongo-db: